### ISSUE TITLE
Internal links that contain the full URL or API URL reloads the full page

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/nextjs-starter#3]
This is client side rendered:

```
<Link href="/blog">Take me to the blog</ Link>
```

But this is server side rendered and reloads the whole page:

```
<Link href="https://localhost:3000/blog">Take me to the blog</ Link>
<Link href="https://headless-wordpress.lndo.site/blog">Take me to the blog</ Link>
```

**Comment by luukdv** [comment]
This is because the API returns the complete WP content as a string. There are two solutions:

- Take advantage of Gutenberg blocks and let the API return each block as a separate item with a `type`;
- Interpret the content manually, something like this (instead of https://github.com/trendwerk/nextjs-starter/blob/master/components/Content.js):

```
const start = (text, first) => text.indexOf(first) === 0

export default function ({ content }) {
  const parts = content.split('\n').filter(p => p)

  return parts.map((html, key) => {
    // Paragraph
    if (start(html, '<p')) {
      return <p key={key}>...</p>
    // Heading 2
    } else if (start(html, '<h2')) {
      return <h2 key={key}>...</h2>
    // Link
    } else if (start(html, '<div class="wp-block-button')) {
      return <h3 key={key}>...</h3>
    }
  })
}
```

In both cases JSX can be utilized, so we'll have full control over the content output.
